// admin/src/views/IPsView.vue
<script setup lang="ts">
import { computed, ref } from 'vue'
import IconCancel from '~icons/pixelarticons/cancel'
import IconChecklist from '~icons/pixelarticons/checklist'
import IconGlobe from '~icons/pixelarticons/globe'
import IconReload from '~icons/pixelarticons/reload'
import type { IpDetail, IpRow } from '@/api/types'
import { useDetail } from '@/composables/useDetail'
import { usePagedList } from '@/composables/usePagedList'
import { formatDateTime, timeAgo } from '@/lib/dates'
import { formatNumber, isOn } from '@/lib/format'
import { useSession } from '@/stores/session'
import AppDialog from '@/components/ui/AppDialog.vue'
import CountryTag from '@/components/ui/CountryTag.vue'
import IpText from '@/components/ui/IpText.vue'
import ListFrame from '@/components/ui/ListFrame.vue'
import PageHeader from '@/components/ui/PageHeader.vue'
import PlayerHead from '@/components/ui/PlayerHead.vue'
import SearchBox from '@/components/ui/SearchBox.vue'

const session = useSession()
const list = usePagedList<IpRow, { search: string }>({ action: 'get_ips', filters: { search: '' } })

const selected = ref<IpRow | null>(null)
const detail = useDetail<IpDetail>()
/** `ip` puede venir como objeto con los datos o solo como texto: se completa con la fila. */
const info = computed<IpRow | null>(() => {
  const raw = detail.data.value?.ip
  return raw && typeof raw === 'object' ? { ...selected.value, ...raw } : selected.value
})

function open(row: IpRow): void {
  selected.value = row
  void detail.load('get_ip_detail', { ip: row.ip })
}

function close(): void {
  detail.cancel()
  selected.value = null
}
</script>

<template>
  <div>
    <PageHeader title="IPs" :icon="IconGlobe" desc="Direcciones vistas en la red, con cuántos jugadores y conexiones comparten cada una." />

    <ListFrame :list="list" label="Lista de IPs" :empty-icon="IconGlobe" empty-title="No hay IPs que mostrar">
      <template #toolbar>
        <SearchBox v-model="list.filters.search" label="Buscar IPs" placeholder="IP o parte de ella…" />
      </template>

      <table class="tabla">
        <thead>
          <tr>
            <th scope="col">IP</th>
            <th scope="col">País</th>
            <th scope="col">ISP</th>
            <th scope="col">AS</th>
            <th scope="col" class="der">Jugadores</th>
            <th scope="col" class="der">Conexiones</th>
            <th scope="col">Listas</th>
            <th scope="col">Primera vez</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="(row, index) in list.items" :key="row.ip ?? index">
            <td>
              <button type="button" class="enlace-fila" aria-label="Ver jugadores de esta IP" @click="open(row)"><IpText :ip="row.ip" /></button>
            </td>
            <td><CountryTag :code="row.country_code" :name="row.country" /></td>
            <td class="celda-texto truncate">{{ row.isp || '—' }}</td>
            <td class="mono">{{ row.asn || '—' }}</td>
            <td class="der num">{{ formatNumber(row.player_count) }}</td>
            <td class="der num">{{ formatNumber(row.connection_count) }}</td>
            <td>
              <span class="chips">
                <span v-if="isOn(row.is_whitelisted)" class="chip accent"><IconChecklist aria-hidden="true" />WL</span>
                <span v-if="isOn(row.is_blacklisted)" class="chip down"><IconCancel aria-hidden="true" />BL</span>
                <span v-if="!isOn(row.is_whitelisted) && !isOn(row.is_blacklisted)" class="faint">—</span>
              </span>
            </td>
            <td class="nowrap" :title="formatDateTime(row.first_seen)">{{ timeAgo(row.first_seen) }}</td>
          </tr>
        </tbody>
      </table>
    </ListFrame>

    <AppDialog :open="selected !== null" :icon="IconGlobe" title="Detalle de la IP" @close="close">
      <div class="modal-cuerpo">
        <dl v-if="info" class="detalles">
          <div class="detalle"><dt class="label">IP</dt><dd class="valor"><IpText :ip="info.ip" /></dd></div>
          <div class="detalle"><dt class="label">País</dt><dd class="valor"><CountryTag :code="info.country_code" :name="info.country" show-name /></dd></div>
          <div class="detalle"><dt class="label">ISP</dt><dd class="valor">{{ info.isp || '—' }}</dd></div>
          <div class="detalle"><dt class="label">AS</dt><dd class="valor mono">{{ info.asn || '—' }}</dd></div>
        </dl>
        <p v-if="detail.loading.value" class="faint" aria-busy="true">Cargando jugadores…</p>
        <div v-else-if="detail.error.value" class="aviso down" role="alert">
          <span class="texto">{{ detail.error.value }}</span>
          <button v-if="selected" type="button" class="btn sm" @click="open(selected)"><IconReload aria-hidden="true" /> Reintentar</button>
        </div>
        <template v-else-if="detail.data.value">
          <h3>Jugadores que la han usado</h3>
          <p v-if="!detail.data.value.players.length" class="faint">Ningún jugador registrado.</p>
          <ul v-else class="jugadores">
            <li v-for="player in detail.data.value.players" :key="player.uuid">
              <PlayerHead :id="player.uuid" :name="player.nick" />
              <RouterLink v-if="session.can('players')" class="enlace-fila" :to="{ name: 'player', params: { uuid: player.uuid } }">{{ player.nick }}</RouterLink>
              <span v-else>{{ player.nick }}</span>
              <span class="faint">{{ timeAgo(player.last_used) }}</span>
            </li>
          </ul>
        </template>
      </div>
      <footer class="modal-pie">
        <button type="button" class="btn primary" @click="close">Cerrar</button>
      </footer>
    </AppDialog>
  </div>
</template>

<style scoped>
dl, dd { margin: 0; }
.jugadores { list-style: none; margin: 0; padding: 0; display: grid; gap: 8px; }
.jugadores li { display: flex; align-items: center; gap: 10px; font-size: var(--text-sm); }
.jugadores .faint { margin-left: auto; font-size: var(--text-xs); }
</style>

// Product/resources/scripts/components/furrguard/views/IpsView.tsx
import React, { useState } from 'react';
import { faBan, faClipboardCheck, faGlobe } from '@fortawesome/free-solid-svg-icons';
import { IpDetail, IpRow } from '@/api/furrguard/types';
import { Dialog } from '@/components/elements/dialog';
import { Button } from '@/components/elements/button/index';
import PageHeader from '@/components/elements/ui/PageHeader';
import { useFurrGuard } from '@/components/furrguard/FurrGuardContext';
import { useDetail, usePagedList } from '@/components/furrguard/hooks';
import { formatDateTime, formatNumber, isOn, timeAgo } from '@/components/furrguard/lib/format';
import { playerPath, sectionInfo } from '@/components/furrguard/sections';
import {
    Chip,
    Chips,
    CountryTag,
    Detail,
    DetailList,
    IpText,
    ListFrame,
    Mono,
    Muted,
    PanelText,
    PlayerHead,
    RetryNotice,
    RowButton,
    RowLink,
    RowMain,
    Rows,
    SearchBox,
    Skeleton,
    Stack,
} from '@/components/furrguard/ui';

const IpsView = () => {
    const { can } = useFurrGuard();
    const info = sectionInfo('ips');
    const list = usePagedList<IpRow, { search: string }>({ action: 'get_ips', filters: { search: '' } });
    const [selected, setSelected] = useState<IpRow | null>(null);
    const detail = useDetail<IpDetail>();

    /** `ip` may come as an object with the data or just as text: complete it with the row. */
    const raw = detail.data?.ip;
    const ipInfo: IpRow | null = raw && typeof raw === 'object' ? { ...(selected as IpRow), ...raw } : selected;

    const open = (row: IpRow) => {
        setSelected(row);
        detail.load('get_ip_detail', { ip: row.ip });
    };

    const close = () => {
        detail.cancel();
        setSelected(null);
    };

    return (
        <Stack>
            <PageHeader title={info.label} description={info.description} />
            <ListFrame
                list={list}
                label={'Lista de IPs'}
                emptyIcon={faGlobe}
                emptyTitle={'No hay IPs que mostrar'}
                toolbar={<SearchBox value={list.filters.search} onChange={(value) => list.setFilter('search', value)} label={'Buscar IPs'} placeholder={'IP o parte de ella…'} />}
            >
                <thead>
                    <tr>
                        <th>IP</th>
                        <th>País</th>
                        <th>ISP</th>
                        <th>AS</th>
                        <th className={'right'}>Jugadores</th>
                        <th className={'right'}>Conexiones</th>
                        <th>Listas</th>
                        <th>Primera vez</th>
                    </tr>
                </thead>
                <tbody>
                    {list.items.map((row, index) => (
                        <tr key={row.ip ?? index}>
                            <td>
                                <RowButton type={'button'} onClick={() => open(row)} aria-label={'Ver jugadores de esta IP'}>
                                    <IpText ip={row.ip} />
                                </RowButton>
                            </td>
                            <td>
                                <CountryTag code={row.country_code} name={row.country} />
                            </td>
                            <td className={'text'}>{row.isp || <Muted>—</Muted>}</td>
                            <td>
                                <Mono>{row.asn || '—'}</Mono>
                            </td>
                            <td className={'right'}>{formatNumber(row.player_count)}</td>
                            <td className={'right'}>{formatNumber(row.connection_count)}</td>
                            <td>
                                <Chips>
                                    {isOn(row.is_whitelisted) && (
                                        <Chip tone={'accent'} icon={faClipboardCheck}>
                                            WL
                                        </Chip>
                                    )}
                                    {isOn(row.is_blacklisted) && (
                                        <Chip tone={'down'} icon={faBan}>
                                            BL
                                        </Chip>
                                    )}
                                    {!isOn(row.is_whitelisted) && !isOn(row.is_blacklisted) && <Muted>—</Muted>}
                                </Chips>
                            </td>
                            <td className={'nowrap'} title={formatDateTime(row.first_seen)}>
                                {timeAgo(row.first_seen)}
                            </td>
                        </tr>
                    ))}
                </tbody>
            </ListFrame>

            <Dialog open={selected !== null} onClose={close} title={'Detalle de la IP'}>
                <div className={'mt-2 flex flex-col gap-4'}>
                    {ipInfo && (
                        <DetailList>
                            <Detail label={'IP'}>
                                <IpText ip={ipInfo.ip} />
                            </Detail>
                            <Detail label={'País'}>
                                <CountryTag code={ipInfo.country_code} name={ipInfo.country} showName />
                            </Detail>
                            <Detail label={'ISP'}>{ipInfo.isp || '—'}</Detail>
                            <Detail label={'AS'} mono>
                                {ipInfo.asn || '—'}
                            </Detail>
                        </DetailList>
                    )}
                    {detail.loading ? (
                        <Skeleton rows={3} />
                    ) : detail.error ? (
                        <RetryNotice title={'No se pudieron cargar los jugadores'} message={detail.error} onRetry={() => selected && open(selected)} />
                    ) : detail.data ? (
                        <div>
                            <h3 className={'text-sm font-semibold mb-2'}>Jugadores que la han usado</h3>
                            {detail.data.players.length === 0 ? (
                                <PanelText className={'px-0'}>Ningún jugador registrado.</PanelText>
                            ) : (
                                <Rows>
                                    {detail.data.players.map((player) => (
                                        <li key={player.uuid}>
                                            <PlayerHead id={player.uuid} name={player.nick} />
                                            <RowMain>{can('players') ? <RowLink to={playerPath(player.uuid)}>{player.nick}</RowLink> : player.nick}</RowMain>
                                            <Muted className={'text-xs'}>{timeAgo(player.last_used)}</Muted>
                                        </li>
                                    ))}
                                </Rows>
                            )}
                        </div>
                    ) : null}
                </div>
                <Dialog.Footer>
                    <Button onClick={close}>Cerrar</Button>
                </Dialog.Footer>
            </Dialog>
        </Stack>
    );
};

export default IpsView;
