// admin/src/views/players/PlayerDetailView.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref, shallowRef } from 'vue'
import IconCancel from '~icons/pixelarticons/cancel'
import IconChecklist from '~icons/pixelarticons/checklist'
import IconCircleQuestion from '~icons/pixelarticons/circle-question'
import IconCrown from '~icons/pixelarticons/crown'
import IconGlobe from '~icons/pixelarticons/globe'
import IconLabel from '~icons/pixelarticons/label'
import IconPlug from '~icons/pixelarticons/plug'
import IconReload from '~icons/pixelarticons/reload'
import IconTrash from '~icons/pixelarticons/trash'
import IconUnlock from '~icons/pixelarticons/unlock'
import { api, ApiError, isAbortError } from '@/api/client'
import type { BlacklistRef, PlayerDetail, WhitelistRef } from '@/api/types'
import { useBusy } from '@/composables/useBusy'
import { banExpiry, banStatus } from '@/lib/bans'
import { confirmAction } from '@/lib/confirm'
import { detailCrumb } from '@/lib/crumb'
import { formatDateTime, timeAgo } from '@/lib/dates'
import { entryLabel } from '@/lib/entries'
import { formatNumber, isOn } from '@/lib/format'
import { reasonLabel } from '@/lib/labels'
import { useSession } from '@/stores/session'
import BanDialog, { type BanDraft } from '@/components/dialogs/BanDialog.vue'
import WhitelistDialog, { type WhitelistDraft } from '@/components/dialogs/WhitelistDialog.vue'
import ActiveSwitch from '@/components/ui/ActiveSwitch.vue'
import CopyField from '@/components/ui/CopyField.vue'
import CountryTag from '@/components/ui/CountryTag.vue'
import EmptyState from '@/components/ui/EmptyState.vue'
import IpText from '@/components/ui/IpText.vue'
import PlayerHead from '@/components/ui/PlayerHead.vue'
import StatusChip from '@/components/ui/StatusChip.vue'
import NameHistoryPanel from './NameHistoryPanel.vue'

const props = defineProps<{ uuid: string }>()
const session = useSession()
const { busy, run } = useBusy()

const detail = shallowRef<PlayerDetail | null>(null)
const loading = ref(true)
const error = shallowRef<ApiError | null>(null)
const whitelistDraft = shallowRef<WhitelistDraft | null>(null)
const banDraft = shallowRef<BanDraft | null>(null)
let controller: AbortController | null = null

async function load(): Promise<void> {
  controller?.abort()
  const current = new AbortController()
  controller = current
  loading.value = true
  error.value = null
  try {
    const result = await api<PlayerDetail>('get_player_detail', { uuid: props.uuid }, { signal: current.signal })
    detail.value = result
    detailCrumb.value = result.player.last_nick
  } catch (e) {
    if (isAbortError(e)) return
    detail.value = null
    error.value = e instanceof ApiError ? e : new ApiError(0, 'unexpected', 'No se pudo cargar el jugador.')
  } finally {
    if (controller === current) {
      controller = null
      loading.value = false
    }
  }
}

onMounted(load)
onBeforeUnmount(() => controller?.abort())

const player = computed(() => detail.value?.player ?? null)
const isPremium = computed(() => detail.value?.premium.status === 'premium')
const premium = computed(() => {
  switch (detail.value?.premium.status) {
    case 'premium': return { label: 'Premium', icon: IconCrown, tone: 'gold' as const }
    case 'not_found': return { label: 'No premium', icon: IconUnlock, tone: 'tenue' as const }
    default: return { label: 'Premium desconocido', icon: IconCircleQuestion, tone: 'tenue' as const }
  }
})

/** Premium → por UUID; no premium → por nick (su UUID offline cambia si cambia el nombre). */
function openWhitelist(): void {
  if (!player.value) return
  whitelistDraft.value = isPremium.value
    ? { type: 'uuid', value: player.value.uuid, reason: '' }
    : { type: 'nick', value: player.value.last_nick, reason: '' }
}

function openBan(): void {
  if (!player.value) return
  banDraft.value = isPremium.value ? { type: 'uuid', value: player.value.uuid } : { type: 'nick', value: player.value.last_nick }
}

async function afterSave(): Promise<void> {
  whitelistDraft.value = null
  banDraft.value = null
  await load()
}

async function removeWhitelist(entry: WhitelistRef): Promise<void> {
  const ok = await confirmAction({ title: 'Quitar de la whitelist', message: `Se eliminará la entrada ${entryLabel(entry.type)} «${entry.value}».`, confirmText: 'Quitar', danger: true })
  if (ok && (await run(`wl-${entry.id}`, () => api('remove_whitelist', { id: entry.id }), 'Entrada de whitelist eliminada.'))) await load()
}

async function toggleBan(entry: BlacklistRef, active: boolean): Promise<void> {
  if (await run(`bl-${entry.id}`, () => api('set_blacklist_active', { id: entry.id, active }), active ? 'Baneo activado.' : 'Baneo desactivado.')) await load()
}

async function removeBan(entry: BlacklistRef): Promise<void> {
  const ok = await confirmAction({ title: 'Eliminar baneo', message: `Se borrará el baneo ${entry.ban_id} y sus IPs hijas. No se puede deshacer.`, confirmText: 'Eliminar', danger: true })
  if (ok && (await run(`bl-${entry.id}`, () => api('remove_blacklist', { id: entry.id }), 'Baneo eliminado.'))) await load()
}
</script>

<template>
  <div>
    <EmptyState v-if="error" tone="error" :title="error.status === 404 ? 'Jugador no encontrado' : 'No se pudo cargar el jugador'" :text="error.message">
      <RouterLink class="btn" :to="{ name: 'players' }">Volver a jugadores</RouterLink>
      <button v-if="error.status !== 404" type="button" class="btn" @click="load"><IconReload aria-hidden="true" /> Reintentar</button>
    </EmptyState>

    <div v-else-if="!detail || !player" class="panel ficha" aria-busy="true">
      <span class="sr-only">Cargando…</span>
      <span class="esqueleto" /><span class="esqueleto" />
    </div>

    <template v-else>
      <section class="panel ficha">
        <PlayerHead :id="player.uuid" :name="player.last_nick" size="lg" />
        <div class="ficha-datos">
          <div class="ficha-nombre">
            <h1>{{ player.last_nick }}</h1>
            <span v-if="isOn(player.is_online)" class="chip ok"><span class="baliza viva" />Online</span>
            <StatusChip v-bind="premium" />
            <span v-if="isOn(player.is_whitelisted)" class="chip accent"><IconChecklist aria-hidden="true" />Whitelist</span>
            <span v-if="isOn(player.is_blacklisted)" class="chip down"><IconCancel aria-hidden="true" />Blacklist</span>
          </div>
          <CopyField :value="player.uuid" label="UUID" />
          <div class="ficha-meta">
            <span>Primera vez <b :title="formatDateTime(player.first_seen)">{{ timeAgo(player.first_seen) }}</b></span>
            <span>Última vez <b :title="formatDateTime(player.last_seen)">{{ timeAgo(player.last_seen) }}</b></span>
            <span>Conexiones <b>{{ formatNumber(player.total_connections) }}</b></span>
            <span v-if="session.canSeeIps">Última IP <b><IpText :ip="player.last_ip" :hidden-by-server="detail.ip_hidden" /></b></span>
            <span>País <b><CountryTag :code="player.last_country_code" :name="player.last_country" show-name /></b></span>
          </div>
        </div>
        <div class="ficha-acciones">
          <button v-if="session.can('whitelist')" type="button" class="btn" @click="openWhitelist"><IconChecklist aria-hidden="true" /> Whitelist</button>
          <button v-if="session.can('blacklist')" type="button" class="btn danger" @click="openBan"><IconCancel aria-hidden="true" /> Banear</button>
        </div>
      </section>

      <div class="rejilla dos seccion">
        <section class="panel">
          <header class="panel-cab"><div class="titulo"><IconChecklist aria-hidden="true" /><h2>Whitelist</h2></div></header>
          <p v-if="!detail.whitelist_entries.length" class="panel-cuerpo faint">No tiene entradas de whitelist.</p>
          <ul v-else class="entradas">
            <li v-for="entry in detail.whitelist_entries" :key="entry.id">
              <span class="chip tenue">{{ entryLabel(entry.type) }}</span>
              <span class="mono valor">{{ entry.value }}</span>
              <button v-if="session.can('whitelist')" type="button" class="btn ghost icono sm" :aria-label="`Quitar ${entry.value} de la whitelist`" :aria-busy="busy === `wl-${entry.id}`" @click="removeWhitelist(entry)">
                <IconTrash aria-hidden="true" />
              </button>
            </li>
          </ul>
        </section>

        <section class="panel">
          <header class="panel-cab"><div class="titulo"><IconCancel aria-hidden="true" /><h2>Baneos</h2></div></header>
          <p v-if="!detail.blacklist_entries.length" class="panel-cuerpo faint">No tiene baneos.</p>
          <ul v-else class="entradas">
            <li v-for="entry in detail.blacklist_entries" :key="entry.id">
              <span class="mono faint">{{ entry.ban_id }}</span>
              <span class="valor">
                <span class="mono">{{ entryLabel(entry.type) }} · {{ entry.value }}</span>
                <span class="sub-celda">{{ entry.reason || 'Sin motivo' }}</span>
              </span>
              <StatusChip v-bind="banStatus(entry.active, entry.expires_at)" />
              <StatusChip v-bind="banExpiry(entry.expires_at)" />
              <template v-if="session.can('blacklist')">
                <ActiveSwitch :active="isOn(entry.active)" :busy="busy === `bl-${entry.id}`" :label="`Baneo ${entry.ban_id} activo`" @change="toggleBan(entry, $event)" />
                <button type="button" class="btn ghost icono sm" :aria-label="`Eliminar baneo ${entry.ban_id}`" @click="removeBan(entry)"><IconTrash aria-hidden="true" /></button>
              </template>
            </li>
          </ul>
        </section>

        <section class="panel">
          <header class="panel-cab"><div class="titulo"><IconLabel aria-hidden="true" /><h2>Nicks usados</h2></div></header>
          <p v-if="!detail.nicks.length" class="panel-cuerpo faint">Sin nicks registrados.</p>
          <ul v-else class="entradas">
            <li v-for="nick in detail.nicks" :key="nick.nick">
              <b class="mono valor">{{ nick.nick }}</b>
              <span class="faint" :title="formatDateTime(nick.last_used)">{{ formatDateTime(nick.first_used) }} → {{ timeAgo(nick.last_used) }}</span>
            </li>
          </ul>
        </section>

        <NameHistoryPanel :player-name="player.last_nick" />
      </div>

      <section v-if="session.canSeeIps" class="panel seccion">
        <header class="panel-cab"><div class="titulo"><IconGlobe aria-hidden="true" /><h2>IPs</h2></div></header>
        <p v-if="detail.ip_hidden || !detail.ips.length" class="panel-cuerpo faint">{{ detail.ip_hidden ? 'Tu rol no puede ver las IPs.' : 'Sin IPs registradas.' }}</p>
        <div v-else class="tabla-marco">
          <table class="tabla">
            <thead><tr><th scope="col">IP</th><th scope="col">País</th><th scope="col">ISP</th><th scope="col">Primera vez</th><th scope="col">Última vez</th></tr></thead>
            <tbody>
              <tr v-for="(ip, index) in detail.ips" :key="ip.ip ?? index">
                <td><IpText :ip="ip.ip" /></td>
                <td><CountryTag :code="ip.country_code" :name="ip.country" show-name /></td>
                <td class="celda-texto truncate">{{ ip.isp || '—' }}</td>
                <td class="nowrap">{{ formatDateTime(ip.first_used) }}</td>
                <td class="nowrap" :title="formatDateTime(ip.last_used)">{{ timeAgo(ip.last_used) }}</td>
              </tr>
            </tbody>
          </table>
        </div>
      </section>

      <section class="panel seccion">
        <header class="panel-cab"><div class="titulo"><IconPlug aria-hidden="true" /><h2>Conexiones recientes</h2></div></header>
        <p v-if="!detail.recent_connections.length" class="panel-cuerpo faint">Sin conexiones registradas.</p>
        <div v-else class="tabla-marco">
          <table class="tabla">
            <thead><tr><th scope="col">Fecha</th><th v-if="session.canSeeIps" scope="col">IP</th><th scope="col">País</th><th scope="col">Nick</th><th scope="col">Resultado</th></tr></thead>
            <tbody>
              <tr v-for="connection in detail.recent_connections" :key="connection.id" :class="{ bloqueada: isOn(connection.blocked) }">
                <td class="nowrap">{{ formatDateTime(connection.created_at) }}</td>
                <td v-if="session.canSeeIps"><IpText :ip="connection.ip" /></td>
                <td><CountryTag :code="connection.country_code" :name="connection.country" /></td>
                <td class="mono">{{ connection.nick }}</td>
                <td><StatusChip v-bind="reasonLabel(isOn(connection.blocked) ? connection.block_reason : 'allowed')" /></td>
              </tr>
            </tbody>
          </table>
        </div>
      </section>

      <WhitelistDialog :open="whitelistDraft !== null" :draft="whitelistDraft" @close="whitelistDraft = null" @saved="afterSave" />
      <BanDialog :open="banDraft !== null" :draft="banDraft" @close="banDraft = null" @saved="afterSave" />
    </template>

    <p class="sr-only" aria-live="polite">{{ loading ? 'Cargando jugador…' : '' }}</p>
  </div>
</template>

<style scoped>
.ficha { display: flex; align-items: flex-start; gap: 18px; flex-wrap: wrap; padding: 20px; }
.ficha .esqueleto { width: 40%; }
.ficha-datos { display: grid; gap: 10px; flex: 1 1 320px; min-width: 0; }
.ficha-nombre { display: flex; align-items: center; gap: 10px; flex-wrap: wrap; }
.ficha-nombre h1 { font-size: 24px; overflow-wrap: anywhere; }
.ficha-datos .copiable { width: max-content; max-width: 100%; }
.ficha-meta { display: flex; flex-wrap: wrap; gap: 6px 18px; color: var(--ink-3); font-size: var(--text-sm); }
.ficha-meta b { color: var(--ink-2); font-weight: 500; }
.ficha-acciones { display: flex; gap: 8px; flex-wrap: wrap; }
.entradas { list-style: none; margin: 0; padding: 0; }
.entradas li { display: flex; align-items: center; gap: 10px; flex-wrap: wrap; padding: 10px 18px; border-bottom: 1px solid var(--rule); font-size: var(--text-sm); }
.entradas li:last-child { border-bottom: 0; }
.entradas .valor { flex: 1; min-width: 0; overflow-wrap: anywhere; }
</style>

// Product/resources/scripts/components/furrguard/views/PlayerDetailView.tsx
import React, { useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import styled from 'styled-components/macro';
import tw from 'twin.macro';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import {
    faBan,
    faClipboardCheck,
    faCrown,
    faExclamationTriangle,
    faGlobe,
    faHistory,
    faPlug,
    faQuestionCircle,
    faTag,
    faTrash,
    faUnlock,
} from '@fortawesome/free-solid-svg-icons';
import { furr, isAbortError } from '@/api/furrguard/client';
import { BlacklistRef, NameHistory, NameHistorySource, PlayerDetail, WhitelistRef } from '@/api/furrguard/types';
import { Button } from '@/components/elements/button/index';
import DataField from '@/components/elements/ui/DataField';
import PageHeader from '@/components/elements/ui/PageHeader';
import { Notice, NoticeBody } from '@/components/server/vault/vaultStyles';
import { useFurrGuard } from '@/components/furrguard/FurrGuardContext';
import { ConfirmDialog } from '@/components/furrguard/dialogs/FormDialog';
import { BanDialog, BanDraft, WhitelistDialog, WhitelistDraft } from '@/components/furrguard/dialogs/ListDialogs';
import { useBusy, useConfirm, useLoader } from '@/components/furrguard/hooks';
import { errorMessage, formatDateTime, formatNumber, isOn, timeAgo } from '@/components/furrguard/lib/format';
import { banExpiry, banStatus, entryLabel, reasonLabel } from '@/components/furrguard/lib/labels';
import { sectionPath } from '@/components/furrguard/sections';
import {
    ActiveSwitch,
    Chip,
    CountryTag,
    EmptyState,
    IconButton,
    IpText,
    Mono,
    Muted,
    OnlineChip,
    PanelText,
    PlayerHead,
    PrimaryLink,
    RowActions,
    RowMain,
    Rows,
    SectionPanel,
    Skeleton,
    Stack,
    StatusChip,
    SubText,
    Table,
    TwoColumns,
} from '@/components/furrguard/ui';

const Card = styled.div`
    ${tw`flex flex-wrap items-start gap-5 p-5 rounded-[var(--border-radius)]`};
    background-color: var(--color-background-secondary);
    border: 1px solid var(--color-neutral);
`;

const CardBody = styled.div`
    ${tw`flex flex-col gap-3 flex-1 min-w-0`};
    flex-basis: 20rem;
`;

const NameLine = styled.div`
    ${tw`flex flex-wrap items-center gap-2`};

    h1 {
        ${tw`text-2xl font-semibold`};
        color: var(--color-base);
        overflow-wrap: anywhere;
    }
`;

const Meta = styled.div`
    ${tw`flex flex-wrap gap-x-5 gap-y-1 text-sm`};
    color: var(--color-muted);

    b {
        ${tw`font-medium`};
        color: var(--color-base);
    }
`;

const Actions = styled.div`
    ${tw`flex flex-wrap gap-2`};
`;

const SOURCE_LABELS: Record<NameHistorySource, string> = { mojang: 'Mojang', laby: 'Laby', namemc: 'NameMC' };

/** External services (Mojang, Laby, NameMC) are only queried on demand. */
const NameHistoryPanel = ({ playerName }: { playerName: string }) => {
    const { interceptError } = useFurrGuard();
    const [history, setHistory] = useState<NameHistory | null>(null);
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState('');

    const load = () => {
        setLoading(true);
        setError('');
        setHistory(null);
        furr<NameHistory>('get_name_history', { player_name: playerName })
            .then(setHistory)
            .catch((e) => {
                if (isAbortError(e) || interceptError(e)) return;
                setError(errorMessage(e, 'No se pudo consultar el historial.'));
            })
            .then(() => setLoading(false));
    };

    const failed = history && history.complete === false ? history.failed_sources.map((source) => SOURCE_LABELS[source] ?? source).join(', ') : '';

    return (
        <SectionPanel
            icon={faHistory}
            title={'Historial de nombres'}
            actions={
                <Button size={Button.Sizes.Small} variant={Button.Variants.Secondary} onClick={load} disabled={loading}>
                    {history ? 'Volver a consultar' : 'Consultar'}
                </Button>
            }
        >
            {error ? (
                <PanelText role={'alert'}>{error}</PanelText>
            ) : loading ? (
                <PanelText aria-busy={'true'}>Consultando…</PanelText>
            ) : !history ? (
                <PanelText>Se consulta a servicios externos (Mojang, Laby, NameMC) solo cuando lo pides.</PanelText>
            ) : (
                <>
                    {failed && (
                        <div className={'px-4 pt-3'}>
                            <Notice $tone={'warning'} role={'status'}>
                                <FontAwesomeIcon icon={faExclamationTriangle} />
                                <NoticeBody>
                                    <strong>Historial posiblemente incompleto</strong>
                                    <p>No se pudo consultar {failed}: puede faltar algún nombre anterior. Vuelve a consultar más tarde.</p>
                                </NoticeBody>
                            </Notice>
                        </div>
                    )}
                    {history.history.length === 0 ? (
                        <PanelText>No hay cambios de nombre registrados.</PanelText>
                    ) : (
                        <Rows>
                            {history.history.map((entry, index) => (
                                <li key={`${entry.name}-${index}`}>
                                    <RowMain>
                                        <Mono className={'font-semibold'}>{entry.name}</Mono>
                                    </RowMain>
                                    <Muted className={'text-xs'}>{entry.changed_at ? formatDateTime(entry.changed_at) : 'Original'}</Muted>
                                </li>
                            ))}
                        </Rows>
                    )}
                </>
            )}
        </SectionPanel>
    );
};

const PlayerDetailView = () => {
    const { uuid } = useParams<{ uuid: string }>();
    const { can, canSeeIps } = useFurrGuard();
    const { busy, run } = useBusy();
    const { confirm, pending, settle } = useConfirm();
    const [whitelistDraft, setWhitelistDraft] = useState<WhitelistDraft | null>(null);
    const [banDraft, setBanDraft] = useState<BanDraft | null>(null);
    const { data: detail, error, reload } = useLoader<PlayerDetail>((signal) => furr<PlayerDetail>('get_player_detail', { uuid }, signal), [uuid]);

    const player = detail?.player ?? null;
    const isPremium = detail?.premium.status === 'premium';
    const premium =
        detail?.premium.status === 'premium'
            ? { label: 'Premium', icon: faCrown, tone: 'gold' as const }
            : detail?.premium.status === 'not_found'
            ? { label: 'No premium', icon: faUnlock, tone: 'neutral' as const }
            : { label: 'Premium desconocido', icon: faQuestionCircle, tone: 'neutral' as const };

    /** Premium → by UUID; not premium → by nick (its offline UUID changes with the name). */
    const openWhitelist = () => {
        if (!player) return;
        setWhitelistDraft(isPremium ? { type: 'uuid', value: player.uuid, reason: '' } : { type: 'nick', value: player.last_nick, reason: '' });
    };

    const openBan = () => {
        if (!player) return;
        setBanDraft(isPremium ? { type: 'uuid', value: player.uuid } : { type: 'nick', value: player.last_nick });
    };

    const afterSave = () => {
        setWhitelistDraft(null);
        setBanDraft(null);
        reload();
    };

    const removeWhitelist = async (entry: WhitelistRef) => {
        const ok = await confirm({ title: 'Quitar de la whitelist', message: `Se eliminará la entrada ${entryLabel(entry.type)} «${entry.value}».`, confirmText: 'Quitar' });
        if (ok && (await run(`wl-${entry.id}`, () => furr('remove_whitelist', { id: entry.id }), 'Entrada de whitelist eliminada.'))) reload();
    };

    const toggleBan = async (entry: BlacklistRef, active: boolean) => {
        if (await run(`bl-${entry.id}`, () => furr('set_blacklist_active', { id: entry.id, active }), active ? 'Baneo activado.' : 'Baneo desactivado.')) reload();
    };

    const removeBan = async (entry: BlacklistRef) => {
        const ok = await confirm({ title: 'Eliminar baneo', message: `Se borrará el baneo ${entry.ban_id} y sus IPs hijas. No se puede deshacer.`, confirmText: 'Eliminar' });
        if (ok && (await run(`bl-${entry.id}`, () => furr('remove_blacklist', { id: entry.id }), 'Baneo eliminado.'))) reload();
    };

    if (error) {
        return (
            <Stack>
                <PageHeader title={'Ficha de jugador'} />
                <EmptyState icon={faExclamationTriangle} tone={'down'} title={error.status === 404 ? 'Jugador no encontrado' : 'No se pudo cargar el jugador'} text={error.message}>
                    <Link to={sectionPath('players')}>
                        <Button variant={Button.Variants.Secondary} size={Button.Sizes.Small}>
                            Volver a jugadores
                        </Button>
                    </Link>
                    {error.status !== 404 && (
                        <Button size={Button.Sizes.Small} onClick={reload}>
                            Reintentar
                        </Button>
                    )}
                </EmptyState>
            </Stack>
        );
    }

    if (!detail || !player) {
        return (
            <Stack>
                <PageHeader title={'Ficha de jugador'} />
                <Skeleton rows={3} />
            </Stack>
        );
    }

    return (
        <Stack>
            <PageHeader
                title={player.last_nick}
                description={
                    <>
                        <PrimaryLink to={sectionPath('players')}>Jugadores</PrimaryLink> › Ficha de jugador
                    </>
                }
            />

            <Card>
                <PlayerHead id={player.uuid} name={player.last_nick} size={72} />
                <CardBody>
                    <NameLine>
                        <h1>{player.last_nick}</h1>
                        {isOn(player.is_online) && <OnlineChip />}
                        <StatusChip {...premium} />
                        {isOn(player.is_whitelisted) && (
                            <Chip tone={'accent'} icon={faClipboardCheck}>
                                Whitelist
                            </Chip>
                        )}
                        {isOn(player.is_blacklisted) && (
                            <Chip tone={'down'} icon={faBan}>
                                Blacklist
                            </Chip>
                        )}
                    </NameLine>
                    <DataField label={'UUID'} value={player.uuid} copyValue={player.uuid} mono />
                    <Meta>
                        <span>
                            Primera vez <b title={formatDateTime(player.first_seen)}>{timeAgo(player.first_seen)}</b>
                        </span>
                        <span>
                            Última vez <b title={formatDateTime(player.last_seen)}>{timeAgo(player.last_seen)}</b>
                        </span>
                        <span>
                            Conexiones <b>{formatNumber(player.total_connections)}</b>
                        </span>
                        {canSeeIps && (
                            <span>
                                Última IP{' '}
                                <b>
                                    <IpText ip={player.last_ip} hiddenByServer={detail.ip_hidden} />
                                </b>
                            </span>
                        )}
                        <span>
                            País{' '}
                            <b>
                                <CountryTag code={player.last_country_code} name={player.last_country} showName />
                            </b>
                        </span>
                    </Meta>
                </CardBody>
                <Actions>
                    {can('whitelist') && (
                        <Button variant={Button.Variants.Secondary} onClick={openWhitelist}>
                            <FontAwesomeIcon icon={faClipboardCheck} />
                            <span className={'ml-2'}>Whitelist</span>
                        </Button>
                    )}
                    {can('blacklist') && (
                        <Button.Danger onClick={openBan}>
                            <FontAwesomeIcon icon={faBan} />
                            <span className={'ml-2'}>Banear</span>
                        </Button.Danger>
                    )}
                </Actions>
            </Card>

            <TwoColumns>
                <SectionPanel icon={faClipboardCheck} title={'Whitelist'}>
                    {detail.whitelist_entries.length === 0 ? (
                        <PanelText>No tiene entradas de whitelist.</PanelText>
                    ) : (
                        <Rows>
                            {detail.whitelist_entries.map((entry) => (
                                <li key={entry.id}>
                                    <Chip>{entryLabel(entry.type)}</Chip>
                                    <RowMain>
                                        <Mono>{entry.value}</Mono>
                                    </RowMain>
                                    {can('whitelist') && (
                                        <IconButton icon={faTrash} label={`Quitar ${entry.value} de la whitelist`} busy={busy === `wl-${entry.id}`} danger onClick={() => removeWhitelist(entry)} />
                                    )}
                                </li>
                            ))}
                        </Rows>
                    )}
                </SectionPanel>

                <SectionPanel icon={faBan} title={'Baneos'}>
                    {detail.blacklist_entries.length === 0 ? (
                        <PanelText>No tiene baneos.</PanelText>
                    ) : (
                        <Rows>
                            {detail.blacklist_entries.map((entry) => (
                                <li key={entry.id}>
                                    <Muted className={'font-mono text-xs'}>{entry.ban_id}</Muted>
                                    <RowMain>
                                        <Mono>
                                            {entryLabel(entry.type)} · {entry.value}
                                        </Mono>
                                        <SubText>{entry.reason || 'Sin motivo'}</SubText>
                                    </RowMain>
                                    <StatusChip {...banStatus(entry.active, entry.expires_at)} />
                                    <StatusChip {...banExpiry(entry.expires_at)} />
                                    {can('blacklist') && (
                                        <RowActions>
                                            <ActiveSwitch active={isOn(entry.active)} busy={busy === `bl-${entry.id}`} label={`Baneo ${entry.ban_id} activo`} onChange={(active) => toggleBan(entry, active)} />
                                            <IconButton icon={faTrash} label={`Eliminar baneo ${entry.ban_id}`} danger onClick={() => removeBan(entry)} />
                                        </RowActions>
                                    )}
                                </li>
                            ))}
                        </Rows>
                    )}
                </SectionPanel>

                <SectionPanel icon={faTag} title={'Nicks usados'}>
                    {detail.nicks.length === 0 ? (
                        <PanelText>Sin nicks registrados.</PanelText>
                    ) : (
                        <Rows>
                            {detail.nicks.map((nick) => (
                                <li key={nick.nick}>
                                    <RowMain>
                                        <Mono className={'font-semibold'}>{nick.nick}</Mono>
                                    </RowMain>
                                    <Muted className={'text-xs'} title={formatDateTime(nick.last_used)}>
                                        {formatDateTime(nick.first_used)} → {timeAgo(nick.last_used)}
                                    </Muted>
                                </li>
                            ))}
                        </Rows>
                    )}
                </SectionPanel>

                <NameHistoryPanel playerName={player.last_nick} />
            </TwoColumns>

            {canSeeIps && (
                <SectionPanel icon={faGlobe} title={'IPs'}>
                    {detail.ip_hidden || detail.ips.length === 0 ? (
                        <PanelText>{detail.ip_hidden ? 'Tu rol no puede ver las IPs.' : 'Sin IPs registradas.'}</PanelText>
                    ) : (
                        <Table>
                            <thead>
                                <tr>
                                    <th>IP</th>
                                    <th>País</th>
                                    <th>ISP</th>
                                    <th>Primera vez</th>
                                    <th>Última vez</th>
                                </tr>
                            </thead>
                            <tbody>
                                {detail.ips.map((ip, index) => (
                                    <tr key={ip.ip ?? index}>
                                        <td>
                                            <IpText ip={ip.ip} />
                                        </td>
                                        <td>
                                            <CountryTag code={ip.country_code} name={ip.country} showName />
                                        </td>
                                        <td className={'text'}>{ip.isp || <Muted>—</Muted>}</td>
                                        <td className={'nowrap'}>{formatDateTime(ip.first_used)}</td>
                                        <td className={'nowrap'} title={formatDateTime(ip.last_used)}>
                                            {timeAgo(ip.last_used)}
                                        </td>
                                    </tr>
                                ))}
                            </tbody>
                        </Table>
                    )}
                </SectionPanel>
            )}

            <SectionPanel icon={faPlug} title={'Conexiones recientes'}>
                {detail.recent_connections.length === 0 ? (
                    <PanelText>Sin conexiones registradas.</PanelText>
                ) : (
                    <Table>
                        <thead>
                            <tr>
                                <th>Fecha</th>
                                {canSeeIps && <th>IP</th>}
                                <th>País</th>
                                <th>Nick</th>
                                <th>Resultado</th>
                            </tr>
                        </thead>
                        <tbody>
                            {detail.recent_connections.map((connection) => (
                                <tr key={connection.id} className={isOn(connection.blocked) ? 'blocked' : undefined}>
                                    <td className={'nowrap'}>{formatDateTime(connection.created_at)}</td>
                                    {canSeeIps && (
                                        <td>
                                            <IpText ip={connection.ip} />
                                        </td>
                                    )}
                                    <td>
                                        <CountryTag code={connection.country_code} name={connection.country} />
                                    </td>
                                    <td>
                                        <Mono>{connection.nick}</Mono>
                                    </td>
                                    <td>
                                        <StatusChip {...reasonLabel(isOn(connection.blocked) ? connection.block_reason : 'allowed')} />
                                    </td>
                                </tr>
                            ))}
                        </tbody>
                    </Table>
                )}
            </SectionPanel>

            <WhitelistDialog draft={whitelistDraft} onClose={() => setWhitelistDraft(null)} onSaved={afterSave} />
            <BanDialog draft={banDraft} onClose={() => setBanDraft(null)} onSaved={afterSave} />
            <ConfirmDialog pending={pending} onSettle={settle} />
        </Stack>
    );
};

export default PlayerDetailView;
