// Product/resources/scripts/components/furrguard/views/BlacklistView.tsx
import React, { useState } from 'react';
import styled from 'styled-components/macro';
import tw from 'twin.macro';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faBan, faChevronDown, faEdit, faGamepad, faPlus, faTrash } from '@fortawesome/free-solid-svg-icons';
import { furr } from '@/api/furrguard/client';
import { BanChild, BanRow } from '@/api/furrguard/types';
import { Button } from '@/components/elements/button/index';
import PageHeader from '@/components/elements/ui/PageHeader';
import { ConfirmDialog } from '@/components/furrguard/dialogs/FormDialog';
import { AddBanIpDialog, BanDialog, BanDraft, BanEditTarget, EditBanDialog, UnifiedBanDialog } from '@/components/furrguard/dialogs/ListDialogs';
import { useBusy, useConfirm, usePagedList } from '@/components/furrguard/hooks';
import { formatDateTime, isOn, timeAgo } from '@/components/furrguard/lib/format';
import { banExpiry, banStatus, ENTRY_TYPES, entryInfo } from '@/components/furrguard/lib/labels';
import { sectionInfo } from '@/components/furrguard/sections';
import { EntryValue } from '@/components/furrguard/views/WhitelistView';
import {
    ActiveSwitch,
    CompactSelect,
    FilterTabs,
    IconButton,
    IpText,
    ListFrame,
    Mono,
    Muted,
    RowActions,
    SearchBox,
    Stack,
    StatusChip,
    SubText,
} from '@/components/furrguard/ui';

const STATUS_TABS = [
    { value: 'all', label: 'Todos' },
    { value: 'active', label: 'Activos' },
    { value: 'inactive', label: 'Inactivos' },
    { value: 'expired', label: 'Expirados' },
] as const;

const Target = styled.div`
    ${tw`flex flex-wrap items-center gap-2`};
`;

const ChildrenToggle = styled.button<{ $open: boolean }>`
    ${tw`inline-flex items-center gap-1 mt-1 text-xs font-medium`};
    color: var(--color-primary);

    svg {
        font-size: 0.6rem;
        transition: transform 150ms ease;
        transform: rotate(${({ $open }) => ($open ? 180 : 0)}deg);
    }
`;

const BlacklistView = () => {
    const info = sectionInfo('blacklist');
    const list = usePagedList<BanRow, { status: string; type: string; search: string }>({
        action: 'get_blacklist',
        filters: { status: 'all', type: '', search: '' },
        allowed: { status: STATUS_TABS.map((t) => t.value), type: ['', ...ENTRY_TYPES.map((t) => t.value)] },
    });
    const { busy, run } = useBusy();
    const { confirm, pending, settle } = useConfirm();
    const [expanded, setExpanded] = useState<Set<number>>(new Set());
    const [unifiedOpen, setUnifiedOpen] = useState(false);
    const [banDraft, setBanDraft] = useState<BanDraft | null>(null);
    const [editTarget, setEditTarget] = useState<BanEditTarget | null>(null);
    const [ipParent, setIpParent] = useState<BanRow | null>(null);

    const toggleChildren = (id: number) => {
        setExpanded((current) => {
            const next = new Set(current);
            if (next.has(id)) next.delete(id);
            else next.add(id);

            return next;
        });
    };

    const setActive = async (row: BanChild, active: boolean) => {
        const text = active ? `Baneo ${row.ban_id} activado.` : `Baneo ${row.ban_id} desactivado.`;
        if (await run(row.id, () => furr('set_blacklist_active', { id: row.id, active }), text)) list.reload();
    };

    const remove = async (row: BanChild, isParent: boolean) => {
        const ok = await confirm({
            title: 'Eliminar baneo',
            message: isParent ? `Se borrará ${row.ban_id} (${row.value}) junto a todas sus IPs hijas. No se puede deshacer.` : `Se borrará la IP hija ${row.value}.`,
            confirmText: 'Eliminar',
        });
        if (ok && (await run(row.id, () => furr('remove_blacklist', { id: row.id }), 'Baneo eliminado.'))) list.reload();
    };

    const saved = () => {
        setUnifiedOpen(false);
        setBanDraft(null);
        setEditTarget(null);
        setIpParent(null);
        list.reload();
    };

    return (
        <Stack>
            <PageHeader
                title={info.label}
                description={info.description}
                actions={
                    <>
                        <Button.Danger onClick={() => setUnifiedOpen(true)}>
                            <FontAwesomeIcon icon={faGamepad} />
                            <span className={'ml-2'}>Banear jugador</span>
                        </Button.Danger>
                        <Button variant={Button.Variants.Secondary} onClick={() => setBanDraft({ type: 'ip', value: '' })}>
                            <FontAwesomeIcon icon={faPlus} />
                            <span className={'ml-2'}>Baneo avanzado</span>
                        </Button>
                    </>
                }
            />
            <ListFrame
                list={list}
                label={'Baneos'}
                emptyIcon={faBan}
                emptyTitle={'No hay baneos con este filtro'}
                toolbar={
                    <>
                        <FilterTabs value={list.filters.status} onChange={(value) => list.setFilter('status', value)} options={STATUS_TABS} label={'Filtrar por estado'} />
                        <SearchBox value={list.filters.search} onChange={(value) => list.setFilter('search', value)} label={'Buscar baneos'} placeholder={'Valor, ID o motivo…'} />
                        <CompactSelect aria-label={'Tipo'} value={list.filters.type} onChange={(event) => list.setFilter('type', event.currentTarget.value)}>
                            <option value={''}>Todos los tipos</option>
                            {ENTRY_TYPES.map((type) => (
                                <option key={type.value} value={type.value}>
                                    {type.label}
                                </option>
                            ))}
                        </CompactSelect>
                    </>
                }
            >
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Objetivo</th>
                        <th>Motivo</th>
                        <th>Estado</th>
                        <th>Expira</th>
                        <th>Creado</th>
                        <th className={'actions'}>
                            <span className={'sr-only'}>Acciones</span>
                        </th>
                    </tr>
                </thead>
                <tbody>
                    {list.items.map((row) => {
                        const type = entryInfo(row.type);
                        const open = expanded.has(row.id);

                        return (
                            <React.Fragment key={row.id}>
                                <tr>
                                    <td>
                                        <Mono>{row.ban_id}</Mono>
                                    </td>
                                    <td>
                                        <Target>
                                            <StatusChip label={type?.label ?? row.type} icon={type?.icon ?? faBan} />
                                            <EntryValue type={row.type} value={row.value} name={row.minecraft_name} />
                                        </Target>
                                        {row.children.length > 0 && (
                                            <ChildrenToggle type={'button'} $open={open} aria-expanded={open} onClick={() => toggleChildren(row.id)}>
                                                <FontAwesomeIcon icon={faChevronDown} />
                                                {row.children.length} {row.children.length === 1 ? 'IP manchada' : 'IPs manchadas'}
                                            </ChildrenToggle>
                                        )}
                                    </td>
                                    <td className={'text'}>
                                        {row.reason || <Muted>—</Muted>}
                                        <SubText>por {row.added_by || 'Sistema'}</SubText>
                                    </td>
                                    <td>
                                        <StatusChip {...banStatus(row.active, row.expires_at)} />
                                    </td>
                                    <td>
                                        <StatusChip {...banExpiry(row.expires_at)} />
                                    </td>
                                    <td className={'nowrap'} title={formatDateTime(row.created_at)}>
                                        {timeAgo(row.created_at)}
                                    </td>
                                    <td className={'actions'}>
                                        <RowActions>
                                            <ActiveSwitch active={isOn(row.active)} busy={busy === row.id} label={`Baneo ${row.ban_id} activo`} onChange={(active) => setActive(row, active)} />
                                            <IconButton icon={faEdit} label={`Editar baneo ${row.ban_id}`} onClick={() => setEditTarget(row)} />
                                            <IconButton icon={faPlus} label={`Añadir IP al baneo ${row.ban_id}`} onClick={() => setIpParent(row)} />
                                            <IconButton icon={faTrash} label={`Eliminar baneo ${row.ban_id}`} danger onClick={() => remove(row, true)} />
                                        </RowActions>
                                    </td>
                                </tr>
                                {open &&
                                    row.children.map((child) => (
                                        <tr key={child.id} className={'child'}>
                                            <td>
                                                <Mono>{child.ban_id}</Mono>
                                            </td>
                                            <td>
                                                <Muted className={'text-xs mr-2'}>IP hija</Muted>
                                                <IpText ip={child.value} />
                                            </td>
                                            <td>
                                                <Muted>Hereda el motivo</Muted>
                                            </td>
                                            <td>
                                                <StatusChip {...banStatus(child.active, child.expires_at)} />
                                            </td>
                                            <td>
                                                <StatusChip {...banExpiry(child.expires_at)} />
                                            </td>
                                            <td />
                                            <td className={'actions'}>
                                                <RowActions>
                                                    <ActiveSwitch active={isOn(child.active)} busy={busy === child.id} label={`IP hija ${child.ban_id} activa`} onChange={(active) => setActive(child, active)} />
                                                    <IconButton icon={faTrash} label={`Eliminar IP hija ${child.ban_id}`} danger onClick={() => remove(child, false)} />
                                                </RowActions>
                                            </td>
                                        </tr>
                                    ))}
                            </React.Fragment>
                        );
                    })}
                </tbody>
            </ListFrame>

            <UnifiedBanDialog open={unifiedOpen} onClose={() => setUnifiedOpen(false)} onSaved={saved} />
            <BanDialog draft={banDraft} onClose={() => setBanDraft(null)} onSaved={saved} />
            <EditBanDialog ban={editTarget} onClose={() => setEditTarget(null)} onSaved={saved} />
            <AddBanIpDialog parent={ipParent} onClose={() => setIpParent(null)} onSaved={saved} />
            <ConfirmDialog pending={pending} onSettle={settle} />
        </Stack>
    );
};

export default BlacklistView;

// admin/src/views/blacklist/BlacklistView.vue
<script setup lang="ts">
import { ref, shallowRef } from 'vue'
import IconChevronDown from '~icons/lucide/chevron-down'
import IconCancel from '~icons/pixelarticons/cancel'
import IconEdit from '~icons/pixelarticons/edit'
import IconGamepad from '~icons/pixelarticons/gamepad'
import IconPlus from '~icons/pixelarticons/plus'
import IconTrash from '~icons/pixelarticons/trash'
import { api } from '@/api/client'
import type { BanChild, BanRow } from '@/api/types'
import { useBusy } from '@/composables/useBusy'
import { usePagedList } from '@/composables/usePagedList'
import { banExpiry, banStatus } from '@/lib/bans'
import { confirmAction } from '@/lib/confirm'
import { formatDateTime, timeAgo } from '@/lib/dates'
import { ENTRY_TYPES, entryInfo } from '@/lib/entries'
import { isOn } from '@/lib/format'
import AddBanIpDialog from '@/components/dialogs/AddBanIpDialog.vue'
import BanDialog, { type BanDraft } from '@/components/dialogs/BanDialog.vue'
import EditBanDialog, { type BanEditTarget } from '@/components/dialogs/EditBanDialog.vue'
import UnifiedBanDialog from '@/components/dialogs/UnifiedBanDialog.vue'
import ActiveSwitch from '@/components/ui/ActiveSwitch.vue'
import FilterTabs from '@/components/ui/FilterTabs.vue'
import IpText from '@/components/ui/IpText.vue'
import ListFrame from '@/components/ui/ListFrame.vue'
import PageHeader from '@/components/ui/PageHeader.vue'
import SearchBox from '@/components/ui/SearchBox.vue'
import StatusChip from '@/components/ui/StatusChip.vue'

const STATUS_TABS = [
  { value: 'all', label: 'Todos' },
  { value: 'active', label: 'Activos' },
  { value: 'inactive', label: 'Inactivos' },
  { value: 'expired', label: 'Expirados' },
] as const

const list = usePagedList<BanRow, { status: string; type: string; search: string }>({
  action: 'get_blacklist',
  filters: { status: 'all', type: '', search: '' },
  allowed: { status: STATUS_TABS.map((t) => t.value), type: ['', ...ENTRY_TYPES.map((t) => t.value)] },
})
const { busy, run } = useBusy()

const expanded = ref(new Set<number>())
const unifiedOpen = ref(false)
const banDraft = shallowRef<BanDraft | null>(null)
const editTarget = shallowRef<BanEditTarget | null>(null)
const ipParent = shallowRef<BanRow | null>(null)

function toggleChildren(id: number): void {
  const next = new Set(expanded.value)
  if (next.has(id)) next.delete(id)
  else next.add(id)
  expanded.value = next
}

async function setActive(row: BanChild, active: boolean): Promise<void> {
  const text = active ? `Baneo ${row.ban_id} activado.` : `Baneo ${row.ban_id} desactivado.`
  if (await run(row.id, () => api('set_blacklist_active', { id: row.id, active }), text)) await list.reload()
}

async function remove(row: BanChild, isParent: boolean): Promise<void> {
  const ok = await confirmAction({
    title: 'Eliminar baneo',
    message: isParent ? `Se borrará ${row.ban_id} (${row.value}) junto a todas sus IPs hijas. No se puede deshacer.` : `Se borrará la IP hija ${row.value}.`,
    confirmText: 'Eliminar',
    danger: true,
  })
  if (ok && (await run(row.id, () => api('remove_blacklist', { id: row.id }), 'Baneo eliminado.'))) await list.reload()
}

async function saved(): Promise<void> {
  unifiedOpen.value = false
  banDraft.value = null
  editTarget.value = null
  ipParent.value = null
  await list.reload()
}
</script>

<template>
  <div>
    <PageHeader title="Blacklist" :icon="IconCancel" desc="Baneos por UUID, nick, IP, rango o AS. Desactivar un baneo desactiva también sus IPs manchadas.">
      <button type="button" class="btn danger" @click="unifiedOpen = true"><IconGamepad aria-hidden="true" /> Banear jugador</button>
      <button type="button" class="btn" @click="banDraft = { type: 'ip', value: '' }"><IconPlus aria-hidden="true" /> Baneo avanzado</button>
    </PageHeader>

    <ListFrame :list="list" label="Baneos" :empty-icon="IconCancel" empty-title="No hay baneos con este filtro">
      <template #toolbar>
        <FilterTabs v-model="list.filters.status" label="Filtrar por estado" :options="STATUS_TABS" />
        <SearchBox v-model="list.filters.search" label="Buscar baneos" placeholder="Valor, ID o motivo…" />
        <label class="sr-only" for="filtro-tipo-ban">Tipo</label>
        <select id="filtro-tipo-ban" v-model="list.filters.type" class="select">
          <option value="">Todos los tipos</option>
          <option v-for="type in ENTRY_TYPES" :key="type.value" :value="type.value">{{ type.label }}</option>
        </select>
      </template>

      <table class="tabla">
        <thead>
          <tr>
            <th scope="col">ID</th>
            <th scope="col">Objetivo</th>
            <th scope="col">Motivo</th>
            <th scope="col">Estado</th>
            <th scope="col">Expira</th>
            <th scope="col">Creado</th>
            <th scope="col" class="acciones"><span class="sr-only">Acciones</span></th>
          </tr>
        </thead>
        <tbody>
          <template v-for="row in list.items" :key="row.id">
            <tr>
              <td class="mono">{{ row.ban_id }}</td>
              <td>
                <div class="objetivo">
                  <StatusChip :label="entryInfo(row.type)?.label ?? row.type" :icon="entryInfo(row.type)?.icon" tone="tenue" />
                  <IpText v-if="row.type === 'ip' || row.type === 'ip_range'" :ip="row.value" />
                  <span v-else class="valor">
                    <b v-if="row.minecraft_name">{{ row.minecraft_name }}</b>
                    <span class="mono" :class="{ 'sub-celda': row.minecraft_name }">{{ row.value }}</span>
                  </span>
                </div>
                <button
                  v-if="row.children.length"
                  type="button"
                  class="btn ghost sm hijas"
                  :aria-expanded="expanded.has(row.id)"
                  :aria-controls="row.children.map((child) => `hija-${child.id}`).join(' ')"
                  @click="toggleChildren(row.id)"
                >
                  <IconChevronDown aria-hidden="true" class="giro" :class="{ abierto: expanded.has(row.id) }" />
                  {{ row.children.length }} {{ row.children.length === 1 ? 'IP manchada' : 'IPs manchadas' }}
                </button>
              </td>
              <td class="celda-texto">{{ row.reason || '—' }}<span class="sub-celda">por {{ row.added_by || 'Sistema' }}</span></td>
              <td><StatusChip v-bind="banStatus(row.active, row.expires_at)" /></td>
              <td><StatusChip v-bind="banExpiry(row.expires_at)" /></td>
              <td class="nowrap" :title="formatDateTime(row.created_at)">{{ timeAgo(row.created_at) }}</td>
              <td class="acciones">
                <span class="fila-acciones">
                  <ActiveSwitch :active="isOn(row.active)" :busy="busy === row.id" :label="`Baneo ${row.ban_id} activo`" @change="setActive(row, $event)" />
                  <button type="button" class="btn ghost icono sm" :aria-label="`Editar baneo ${row.ban_id}`" @click="editTarget = row"><IconEdit aria-hidden="true" /></button>
                  <button type="button" class="btn ghost icono sm" :aria-label="`Añadir IP al baneo ${row.ban_id}`" @click="ipParent = row"><IconPlus aria-hidden="true" /></button>
                  <button type="button" class="btn ghost icono sm" :aria-label="`Eliminar baneo ${row.ban_id}`" @click="remove(row, true)"><IconTrash aria-hidden="true" /></button>
                </span>
              </td>
            </tr>
            <template v-if="expanded.has(row.id)">
              <tr v-for="child in row.children" :id="`hija-${child.id}`" :key="child.id" class="hija">
                <td class="mono">{{ child.ban_id }}</td>
                <td><span class="sangria">IP hija</span> <IpText :ip="child.value" /></td>
                <td class="faint">Hereda el motivo</td>
                <td><StatusChip v-bind="banStatus(child.active, child.expires_at)" /></td>
                <td><StatusChip v-bind="banExpiry(child.expires_at)" /></td>
                <td />
                <td class="acciones">
                  <span class="fila-acciones">
                    <ActiveSwitch :active="isOn(child.active)" :busy="busy === child.id" :label="`IP hija ${child.ban_id} activa`" @change="setActive(child, $event)" />
                    <button type="button" class="btn ghost icono sm" :aria-label="`Eliminar IP hija ${child.ban_id}`" @click="remove(child, false)"><IconTrash aria-hidden="true" /></button>
                  </span>
                </td>
              </tr>
            </template>
          </template>
        </tbody>
      </table>
    </ListFrame>

    <UnifiedBanDialog :open="unifiedOpen" @close="unifiedOpen = false" @saved="saved" />
    <BanDialog :open="banDraft !== null" :draft="banDraft" @close="banDraft = null" @saved="saved" />
    <EditBanDialog :open="editTarget !== null" :ban="editTarget" @close="editTarget = null" @saved="saved" />
    <AddBanIpDialog :open="ipParent !== null" :parent="ipParent" @close="ipParent = null" @saved="saved" />
  </div>
</template>

<style scoped>
.objetivo { display: flex; align-items: center; gap: 8px; flex-wrap: wrap; }
.valor { display: grid; line-height: 1.3; }
.hijas { margin-top: 6px; margin-left: -6px; color: var(--fox); }
.giro { transition: transform var(--t) var(--ease); }
.giro.abierto { transform: rotate(180deg); }
.sangria { color: var(--ink-3); font-size: var(--text-xs); margin-right: 6px; }
</style>
