// Product/resources/scripts/components/furrguard/views/GeoBlocksView.tsx
import React, { useState } from 'react';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faBan, faCheck, faEdit, faPlus, faTrash } from '@fortawesome/free-solid-svg-icons';
import { furr } from '@/api/furrguard/client';
import { Flag, Num } from '@/api/furrguard/types';
import { Button } from '@/components/elements/button/index';
import Input from '@/components/elements/Input';
import Select from '@/components/elements/Select';
import PageHeader from '@/components/elements/ui/PageHeader';
import { useFurrGuard } from '@/components/furrguard/FurrGuardContext';
import { ConfirmDialog, Field, FormDialog } from '@/components/furrguard/dialogs/FormDialog';
import { TextAreaField } from '@/components/furrguard/dialogs/fields';
import { useBusy, useConfirm, usePagedList } from '@/components/furrguard/hooks';
import { formatNumber, isOn } from '@/components/furrguard/lib/format';
import { sectionInfo } from '@/components/furrguard/sections';
import { ActiveSwitch, IconButton, ListFrame, McPreview, Mono, Muted, RowActions, SearchBox, Stack, StatCard, StatsGrid } from '@/components/furrguard/ui';

type Kind = 'country' | 'continent';
type GeoRow = { id: number; kick_message: string | null; block_count: Num; active: Flag } & Record<string, unknown>;

const CONTINENTS = [
    { code: 'AF', name: 'África' },
    { code: 'AN', name: 'Antártida' },
    { code: 'AS', name: 'Asia' },
    { code: 'EU', name: 'Europa' },
    { code: 'NA', name: 'Norteamérica' },
    { code: 'OC', name: 'Oceanía' },
    { code: 'SA', name: 'Sudamérica' },
];

/** Countries and continents: the same view, only the field prefix and actions change (§4.4). */
const GeoBlocksView = ({ kind }: { kind: Kind }) => {
    const { notify } = useFurrGuard();
    const info = sectionInfo(kind === 'country' ? 'countries' : 'continents');
    const one = kind === 'country' ? 'país' : 'continente';
    const list = usePagedList<GeoRow, { search: string }>({
        action: kind === 'country' ? 'get_countries' : 'get_continents',
        filters: { search: '' },
        legacyKey: kind === 'country' ? 'countries' : 'continents',
    });
    const { busy, run } = useBusy();
    const { confirm, pending, settle } = useConfirm();
    const stats = (list.data.stats ?? {}) as Record<string, unknown>;

    const codeOf = (row: GeoRow): string => String(row[`${kind}_code`] ?? '');
    const nameOf = (row: GeoRow): string => String(row[`${kind}_name`] ?? '');

    const [dialogOpen, setDialogOpen] = useState(false);
    const [editing, setEditing] = useState<GeoRow | null>(null);
    const [code, setCode] = useState('');
    const [name, setName] = useState('');
    const [kickMessage, setKickMessage] = useState('');

    const openDialog = (row: GeoRow | null) => {
        setEditing(row);
        setCode(row ? codeOf(row) : '');
        setName(row ? nameOf(row) : '');
        setKickMessage(row?.kick_message ?? '');
        setDialogOpen(true);
    };

    const pickContinent = (value: string) => {
        setCode(value);
        const known = CONTINENTS.find((c) => c.code === value);
        if (known) setName(known.name);
    };

    const submit = async () => {
        const upper = code.trim().toUpperCase();
        if (!/^[A-Z]{2}$/.test(upper) || !name.trim()) throw new Error(`Escribe el código de ${one} (2 letras) y su nombre.`);
        const fields = { [`${kind}_name`]: name.trim(), kick_message: kickMessage.trim() };
        if (editing) await furr(`edit_${kind}`, { id: editing.id, ...fields });
        else await furr(`add_${kind}`, { [`${kind}_code`]: upper, ...fields });
        notify(editing ? 'Cambios guardados.' : `${kind === 'country' ? 'País' : 'Continente'} bloqueado.`, 'success');
        setDialogOpen(false);
        list.reload();
    };

    const toggle = async (row: GeoRow, active: boolean) => {
        if (await run(row.id, () => furr(`toggle_${kind}`, { id: row.id, active }), active ? 'Bloqueo activado.' : 'Bloqueo desactivado.')) list.reload();
    };

    const remove = async (row: GeoRow) => {
        const ok = await confirm({ title: `Desbloquear ${one}`, message: `Se eliminará el bloqueo de ${nameOf(row)} (${codeOf(row)}).`, confirmText: 'Eliminar' });
        if (ok && (await run(row.id, () => furr(`delete_${kind}`, { id: row.id }), 'Bloqueo eliminado.'))) list.reload();
    };

    return (
        <Stack>
            <PageHeader
                title={info.label}
                description={info.description}
                actions={
                    <Button onClick={() => openDialog(null)}>
                        <FontAwesomeIcon icon={faPlus} />
                        <span className={'ml-2'}>Bloquear {one}</span>
                    </Button>
                }
            />

            <StatsGrid $min={140}>
                <StatCard label={'Bloqueados'} value={stats.total} icon={info.icon} />
                <StatCard label={'Activos'} value={stats.active} icon={faCheck} tone={'ok'} />
                <StatCard label={'Expulsiones'} value={stats.total_blocks} icon={faBan} tone={'down'} />
            </StatsGrid>

            <ListFrame
                list={list}
                label={info.label}
                emptyIcon={info.icon}
                emptyTitle={`No hay ningún ${one} bloqueado`}
                toolbar={<SearchBox value={list.filters.search} onChange={(value) => list.setFilter('search', value)} label={`Buscar ${info.label.toLowerCase()}`} placeholder={'Código o nombre…'} />}
            >
                <thead>
                    <tr>
                        <th>Código</th>
                        <th>Nombre</th>
                        <th>Mensaje propio</th>
                        <th className={'right'}>Expulsiones</th>
                        <th>Activo</th>
                        <th className={'actions'}>
                            <span className={'sr-only'}>Acciones</span>
                        </th>
                    </tr>
                </thead>
                <tbody>
                    {list.items.map((row) => (
                        <tr key={row.id}>
                            <td>
                                <Mono>{codeOf(row)}</Mono>
                            </td>
                            <td>{nameOf(row)}</td>
                            <td className={'text'}>{row.kick_message || <Muted>Mensaje genérico</Muted>}</td>
                            <td className={'right'}>{formatNumber(row.block_count)}</td>
                            <td>
                                <ActiveSwitch active={isOn(row.active)} busy={busy === row.id} label={`Bloqueo de ${nameOf(row)} activo`} onChange={(active) => toggle(row, active)} />
                            </td>
                            <td className={'actions'}>
                                <RowActions>
                                    <IconButton icon={faEdit} label={`Editar ${nameOf(row)}`} onClick={() => openDialog(row)} />
                                    <IconButton icon={faTrash} label={`Eliminar ${nameOf(row)}`} danger onClick={() => remove(row)} />
                                </RowActions>
                            </td>
                        </tr>
                    ))}
                </tbody>
            </ListFrame>

            <FormDialog open={dialogOpen} title={editing ? `Editar ${one}` : `Bloquear ${one}`} onClose={() => setDialogOpen(false)} onSubmit={submit}>
                <div className={'grid grid-cols-1 sm:grid-cols-3 gap-4'}>
                    <Field label={'Código'} htmlFor={'geo-code'}>
                        {kind === 'continent' ? (
                            <Select id={'geo-code'} value={code} onChange={(event) => pickContinent(event.currentTarget.value)} disabled={!!editing}>
                                <option value={''} disabled>
                                    Elige…
                                </option>
                                {CONTINENTS.map((c) => (
                                    <option key={c.code} value={c.code}>
                                        {c.code} · {c.name}
                                    </option>
                                ))}
                            </Select>
                        ) : (
                            <Input id={'geo-code'} value={code} onChange={(event) => setCode(event.currentTarget.value)} maxLength={2} placeholder={'ES'} disabled={!!editing} className={'font-mono'} autoFocus />
                        )}
                    </Field>
                    <div className={'sm:col-span-2'}>
                        <Field label={'Nombre'} htmlFor={'geo-name'}>
                            <Input id={'geo-name'} value={name} onChange={(event) => setName(event.currentTarget.value)} maxLength={100} />
                        </Field>
                    </div>
                </div>
                <TextAreaField
                    id={'geo-kick'}
                    label={'Mensaje de expulsión'}
                    value={kickMessage}
                    onChange={setKickMessage}
                    rows={4}
                    maxLength={2000}
                    help={'Admite códigos & y §. Vacío = mensaje genérico de Mensajes.'}
                    optional
                    mono
                />
                {kickMessage && <McPreview text={kickMessage} label={'Vista previa'} />}
            </FormDialog>
            <ConfirmDialog pending={pending} onSettle={settle} />
        </Stack>
    );
};

export default GeoBlocksView;

// admin/src/views/GeoBlocksView.vue
<script setup lang="ts">
/** Países y continentes bloqueados: misma vista, cambian el prefijo de los campos y las acciones (§4.4 «igual que hoy»). */
import { computed, reactive, ref, useId } from 'vue'
import IconCancel from '~icons/pixelarticons/cancel'
import IconCheck from '~icons/pixelarticons/check'
import IconEarth from '~icons/pixelarticons/earth'
import IconEdit from '~icons/pixelarticons/edit'
import IconMap from '~icons/pixelarticons/map'
import IconPlus from '~icons/pixelarticons/plus'
import IconTrash from '~icons/pixelarticons/trash'
import { api } from '@/api/client'
import type { Flag, Num } from '@/api/types'
import { useBusy } from '@/composables/useBusy'
import { usePagedList } from '@/composables/usePagedList'
import { confirmAction } from '@/lib/confirm'
import { formatNumber, isOn } from '@/lib/format'
import { toast } from '@/lib/toast'
import AppDialog from '@/components/ui/AppDialog.vue'
import ActiveSwitch from '@/components/ui/ActiveSwitch.vue'
import ListFrame from '@/components/ui/ListFrame.vue'
import McText from '@/components/ui/McText.vue'
import PageHeader from '@/components/ui/PageHeader.vue'
import SearchBox from '@/components/ui/SearchBox.vue'
import StatCard from '@/components/ui/StatCard.vue'

type Kind = 'country' | 'continent'
type GeoRow = { id: number; kick_message: string | null; block_count: Num; active: Flag } & Record<string, unknown>

const CONTINENTS = [
  { code: 'AF', name: 'África' }, { code: 'AN', name: 'Antártida' }, { code: 'AS', name: 'Asia' }, { code: 'EU', name: 'Europa' },
  { code: 'NA', name: 'Norteamérica' }, { code: 'OC', name: 'Oceanía' }, { code: 'SA', name: 'Sudamérica' },
]

const props = defineProps<{ kind: Kind }>()

const copy = computed(() => props.kind === 'country'
  ? { title: 'Países', one: 'país', icon: IconMap, plural: 'countries', desc: 'Conexiones desde estos países se expulsan con su mensaje (o el genérico si no tiene).' }
  : { title: 'Continentes', one: 'continente', icon: IconEarth, plural: 'continents', desc: 'Bloqueo por continente: se evalúa después de proveedores y países.' })

const list = usePagedList<GeoRow, { search: string }>({
  action: props.kind === 'country' ? 'get_countries' : 'get_continents',
  filters: { search: '' },
  legacyKey: props.kind === 'country' ? 'countries' : 'continents',
})
const { busy, run } = useBusy()
const stats = computed(() => (list.data.stats ?? {}) as Record<string, unknown>)

const code = (row: GeoRow): string => String(row[`${props.kind}_code`] ?? '')
const name = (row: GeoRow): string => String(row[`${props.kind}_name`] ?? '')

const dialogOpen = ref(false)
const editing = ref<GeoRow | null>(null)
const form = reactive({ code: '', name: '', kickMessage: '' })
const saving = ref(false)
const formError = ref('')
const ids = { code: useId(), name: useId(), kick: useId() }

function openDialog(row: GeoRow | null): void {
  editing.value = row
  Object.assign(form, { code: row ? code(row) : '', name: row ? name(row) : '', kickMessage: row?.kick_message ?? '' })
  formError.value = ''
  dialogOpen.value = true
}

function pickContinent(): void {
  form.name = CONTINENTS.find((c) => c.code === form.code)?.name ?? form.name
}

async function submit(): Promise<void> {
  const prefix = props.kind
  if (!/^[A-Z]{2}$/.test(form.code.trim().toUpperCase()) || !form.name.trim()) {
    formError.value = `Escribe el código de ${copy.value.one} (2 letras) y su nombre.`
    return
  }
  saving.value = true
  formError.value = ''
  const fields = { [`${prefix}_name`]: form.name.trim(), kick_message: form.kickMessage.trim() }
  try {
    if (editing.value) await api(`edit_${prefix}`, { id: editing.value.id, ...fields })
    else await api(`add_${prefix}`, { [`${prefix}_code`]: form.code.trim().toUpperCase(), ...fields })
    toast(editing.value ? 'Cambios guardados.' : `${copy.value.one === 'país' ? 'País' : 'Continente'} bloqueado.`, 'ok')
    dialogOpen.value = false
    await list.reload()
  } catch (e) {
    formError.value = e instanceof Error ? e.message : 'No se pudo guardar.'
  } finally {
    saving.value = false
  }
}

async function toggle(row: GeoRow, active: boolean): Promise<void> {
  if (await run(row.id, () => api(`toggle_${props.kind}`, { id: row.id, active }), active ? 'Bloqueo activado.' : 'Bloqueo desactivado.')) await list.reload()
}

async function remove(row: GeoRow): Promise<void> {
  const ok = await confirmAction({ title: `Desbloquear ${copy.value.one}`, message: `Se eliminará el bloqueo de ${name(row)} (${code(row)}).`, confirmText: 'Eliminar', danger: true })
  if (ok && (await run(row.id, () => api(`delete_${props.kind}`, { id: row.id }), 'Bloqueo eliminado.'))) await list.reload()
}
</script>

<template>
  <div>
    <PageHeader :title="copy.title" :icon="copy.icon" :desc="copy.desc">
      <button type="button" class="btn primary" @click="openDialog(null)"><IconPlus aria-hidden="true" /> Bloquear {{ copy.one }}</button>
    </PageHeader>

    <div class="metricas seccion">
      <StatCard label="Bloqueados" :value="stats.total ?? '—'" :icon="copy.icon" />
      <StatCard label="Activos" :value="stats.active ?? '—'" :icon="IconCheck" tone="ok" />
      <StatCard label="Expulsiones" :value="stats.total_blocks ?? '—'" :icon="IconCancel" tone="down" />
    </div>

    <ListFrame :list="list" :label="copy.title" :empty-icon="copy.icon" :empty-title="`No hay ningún ${copy.one} bloqueado`">
      <template #toolbar>
        <SearchBox v-model="list.filters.search" :label="`Buscar ${copy.title.toLowerCase()}`" placeholder="Código o nombre…" />
      </template>

      <table class="tabla">
        <thead>
          <tr>
            <th scope="col">Código</th>
            <th scope="col">Nombre</th>
            <th scope="col">Mensaje propio</th>
            <th scope="col" class="der">Expulsiones</th>
            <th scope="col">Activo</th>
            <th scope="col" class="acciones"><span class="sr-only">Acciones</span></th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="row in list.items" :key="row.id">
            <td class="mono">{{ code(row) }}</td>
            <td>{{ name(row) }}</td>
            <td class="celda-texto truncate">{{ row.kick_message || 'Mensaje genérico' }}</td>
            <td class="der num">{{ formatNumber(row.block_count) }}</td>
            <td><ActiveSwitch :active="isOn(row.active)" :busy="busy === row.id" :label="`Bloqueo de ${name(row)} activo`" @change="toggle(row, $event)" /></td>
            <td class="acciones">
              <span class="fila-acciones">
                <button type="button" class="btn ghost icono sm" :aria-label="`Editar ${name(row)}`" @click="openDialog(row)"><IconEdit aria-hidden="true" /></button>
                <button type="button" class="btn ghost icono sm" :aria-label="`Eliminar ${name(row)}`" @click="remove(row)"><IconTrash aria-hidden="true" /></button>
              </span>
            </td>
          </tr>
        </tbody>
      </table>
    </ListFrame>

    <AppDialog :open="dialogOpen" :icon="copy.icon" wide :title="editing ? `Editar ${copy.one}` : `Bloquear ${copy.one}`" @close="dialogOpen = false">
      <form class="modal-form" novalidate @submit.prevent="submit">
        <div class="modal-cuerpo">
          <div class="formulario fila-dos">
            <div class="campo">
              <label :for="ids.code">Código</label>
              <select v-if="kind === 'continent'" :id="ids.code" v-model="form.code" class="select" :disabled="!!editing" @change="pickContinent">
                <option value="" disabled>Elige…</option>
                <option v-for="c in CONTINENTS" :key="c.code" :value="c.code">{{ c.code }} · {{ c.name }}</option>
              </select>
              <input v-else :id="ids.code" v-model="form.code" class="input mono" maxlength="2" placeholder="ES" :disabled="!!editing" required autofocus>
            </div>
            <div class="campo">
              <label :for="ids.name">Nombre</label>
              <input :id="ids.name" v-model="form.name" class="input" maxlength="100" required>
            </div>
          </div>
          <div class="campo">
            <label :for="ids.kick">Mensaje de expulsión <span class="faint">(opcional)</span></label>
            <textarea :id="ids.kick" v-model="form.kickMessage" class="textarea mono" rows="4" maxlength="2000" />
            <p class="ayuda">Admite códigos &amp; y §. Vacío = mensaje genérico de Mensajes.</p>
            <McText v-if="form.kickMessage" :text="form.kickMessage" />
          </div>
          <p v-if="formError" class="form-error" role="alert">{{ formError }}</p>
        </div>
        <footer class="modal-pie">
          <button type="button" class="btn ghost" @click="dialogOpen = false">Cancelar</button>
          <button type="submit" class="btn primary" :aria-busy="saving" :disabled="saving">Guardar</button>
        </footer>
      </form>
    </AppDialog>
  </div>
</template>

<style scoped>
.fila-dos { grid-template-columns: 160px minmax(0, 1fr); }
@media (max-width: 600px) { .fila-dos { grid-template-columns: minmax(0, 1fr); } }
</style>
